name: Build and Push Corefile Image

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    # Exchange GitHub JWT for a short-lived GCP access token
    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        token_format: access_token
        workload_identity_provider: 'projects/750684753949/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider'
        service_account: 'github-actions-builder@joebuhr-gke-lab-8212ed15.iam.gserviceaccount.com'

    - name: Log in to Artifact Registry
      uses: docker/login-action@v3
      with:
        registry: 'us-central1-docker.pkg.dev'
        username: 'oauth2accesstoken'
        password: ${{ steps.auth.outputs.access_token }}

    - name: Generate Build Timestamp
      id: prep
      run: echo "created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

    - name: Build Docker Image (Local Load)
      uses: docker/build-push-action@v5
      with:
        context: .
        load: true
        tags: |
          us-central1-docker.pkg.dev/joebuhr-gke-lab-8212ed15/corefile-repo/corefile:${{ github.sha }}
          us-central1-docker.pkg.dev/joebuhr-gke-lab-8212ed15/corefile-repo/corefile:latest
        labels: |
          org.opencontainers.image.source=https://github.com/jtb75/corefile
          org.opencontainers.image.created=${{ steps.prep.outputs.created }}

    - name: Download Wiz CLI
      run: |
        curl -o wizcli https://downloads.wiz.io/v1/wizcli/latest/wizcli-linux-amd64
        chmod +x wizcli

    - name: Run Wiz CLI Docker Image Scan
      env:
        WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
        WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}
      run: |
        ./wizcli scan container-image us-central1-docker.pkg.dev/joebuhr-gke-lab-8212ed15/corefile-repo/corefile:${{ github.sha }} \
          --dockerfile ./Dockerfile \
          --policies "Default vulnerabilities policy"

    - name: Push Docker Image to Registry
      run: |
        docker push us-central1-docker.pkg.dev/joebuhr-gke-lab-8212ed15/corefile-repo/corefile:${{ github.sha }}
        docker push us-central1-docker.pkg.dev/joebuhr-gke-lab-8212ed15/corefile-repo/corefile:latest

    - name: Wiz CLI Tagging
      env:
        WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
        WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}
      run: |
        ./wizcli tag us-central1-docker.pkg.dev/joebuhr-gke-lab-8212ed15/corefile-repo/corefile:${{ github.sha }}
